export const DetectionConstants = {
  MISTRAL_MAX_VALUE: 5,
  COHERE_MAX_VALUE: 5,
  GEMINI_MAX_VALUE: 5,
  COLLABORATIVE_MAX_VALUE: 5,
  SIMILARITY_MAX_VALUE: 5,
  FINAL_CLASSIFICATION_MAX_VALUE: 5,
}
