export const DetectionConstants = {
  MISTRAL_MAX_VALUE: 5,
  COHERE_MAX_VALUE: 5,
  DEEPSEEK_MAX_VALUE: 5,
  COLLABORATIVE_MAX_VALUE: 1,
  SIMILARITY_MAX_VALUE: 1,
  FINAL_CLASSIFICATION_MAX_VALUE: 5,
}
