INSERT INTO USERS
	(NAME, EMAIL, PASSWORD, ROLE)
VALUES (
	'Admin',
	'admin@email.vale',
	'$2b$10$NK1nwps2gm0M9sb8qJn6iuHJg4Xb9mMk7QvhjrDVQgbAtX2A4s5eW',
	'{admin,user}'
);

INSERT INTO BULLYING_PHRASE (PHRASE) VALUES
('Vai tomar no [CENSURADO]'),
('Vai se [CENSURADO]'),
('Pega no meu [CENSURADO]'),
('Pega na minha [CENSURADO]'),
('Pega no meu [CENSURADO]'),
('Pega no meu [CENSURADO]'),
('Calaboca seu filho [CENSURADO]'),
('Calaboca seu a[CENSURADO]'),
('Calaboca seu c[CENSURADO]'),
('Calaboca seu m[CENSURADO]'),
('Calaboca seu b[CENSURADO]'),
('Calaboca seu v[CENSURADO]'),
('Calaboca seu ve[CENSURADO]');

INSERT INTO BULLYING_PHRASE (PHRASE) VALUES
('Você é um inútil'),
('Seu trabalho não serve para nada'),
('Ninguém gosta de você aqui'),
('Você não vai crescer na empresa'),
('Eu não confio em você para essa tarefa'),
('Por que você é tão incompetente?'),
('É melhor você pedir demissão'),
('Se continuar assim, vou te demitir'),
('Só faz besteira!'),
('Não é possível que você seja tão burro'),
('Você está desperdiçando nosso tempo'),
('Não sei como te contrataram'),
('Eu posso te substituir a qualquer momento'),
('Você não tem futuro aqui'),
('As pessoas riem de você pelas costas'),
('Você nunca faz nada certo'),
('Essa empresa estaria melhor sem você'),
('Se eu fosse você, teria vergonha'),
('Você nunca aprende nada!'),
('Por que ainda está nessa posição?'),
('Já passou da hora de alguém mais competente assumir'),
('Ninguém confia em você'),
('Seu trabalho é péssimo'),
('Não sei como você ainda está aqui'),
('Você só atrapalha o trabalho dos outros'),
('Sua presença aqui é desnecessária'),
('Seu desempenho é vergonhoso'),
('Você é um peso morto para a equipe'),
('Ninguém quer trabalhar com você'),
('Você é um problema para todos aqui'),
('Se continuar assim, vai ser demitido'),
('Eu teria vergonha de apresentar um trabalho como o seu'),
('Você é patético'),
('Parece que você não quer melhorar'),
('Para que você está aqui, afinal?'),
('Você está aqui por pena'),
('Nunca vi alguém tão incompetente'),
('Você é um erro de contratação'),
('As pessoas te evitam aqui'),
('Seu trabalho é uma piada'),
('Ninguém leva você a sério'),
('Você só faz bobagem'),
('Ninguém conta com você para nada importante'),
('Você só atrasa o trabalho dos outros'),
('É uma vergonha ver alguém como você aqui'),
('Você nunca vai conseguir nada melhor'),
('Você não serve para o trabalho'),
('Não espero nada de bom vindo de você'),
('Você é uma vergonha para a equipe'),
('Sua presença só atrapalha'),
('Você não tem o que é preciso para trabalhar aqui'),
('Não aguento mais lidar com sua incompetência'),
('Você é um fardo para todos nós'),
('Ninguém sente sua falta quando você está fora'),
('Você está sempre atrapalhando'),
('Ninguém quer ouvir sua opinião'),
('Não deveria nem estar aqui'),
('Você só ocupa espaço'),
('Já perdeu sua utilidade aqui'),
('Você nunca chega aos padrões da empresa'),
('Sua performance é um desastre'),
('Ninguém confia em você para algo importante'),
('Não faz diferença se você está aqui ou não'),
('Você está sendo carregado pelo resto da equipe'),
('Não sabe fazer nada direito'),
('Você parece uma criança fazendo o trabalho'),
('Sempre depende dos outros para fazer o seu trabalho'),
('Tudo que você faz precisa ser refeito'),
('Você só sabe criar problemas para os outros'),
('Sinceramente, não vejo futuro para você aqui'),
('Você nunca atende as expectativas'),
('Não sei o que você está fazendo aqui'),
('A empresa não precisa de gente como você'),
('Seu esforço não vale nada'),
('Sua presença só diminui o moral da equipe'),
('Ninguém quer que você esteja aqui'),
('Você só fica onde está por sorte'),
('Ninguém aqui confia em você para algo importante'),
('Só atrapalha o trabalho dos outros'),
('Sua saída seria um alívio para todos'),
('Não temos tempo para você aqui'),
('Você é o elo mais fraco da equipe'),
('Nada do que você faz importa para a empresa'),
('Seu trabalho sempre precisa de correções dos outros'),
('Já deveria ter saído há muito tempo'),
('Você é uma decepção'),
('Parece que nunca faz nada direito'),
('É melhor você não aparecer amanhã');

INSERT INTO BULLYING_PHRASE (PHRASE) VALUES
('Esse professor não sabe nada'),
('A gente aprende mais sem ele aqui'),
('Nem parece que é formado'),
('Qualquer um faria um trabalho melhor'),
('A matéria era boa até ele começar a ensinar'),
('Esse professor só enrola e não ensina nada'),
('Ele deveria se aposentar'),
('Ela não sabe controlar a turma'),
('Esse professor só atrapalha'),
('Você é o pior professor que já tive'),
('Ninguém te respeita mesmo'),
('Só está aqui porque não conseguiu emprego melhor'),
('Você não sabe explicar nada direito'),
('Nem deve gostar do que faz'),
('Você é péssimo no que faz'),
('Por que você não pede demissão?'),
('Você está sempre perdido na aula'),
('Ninguém leva você a sério'),
('Essa aula é uma piada'),
('Você só dá matéria chata'),
('É fácil passar nessa aula com um professor assim'),
('Você nunca responde as perguntas'),
('A gente nem precisa prestar atenção na sua aula'),
('Não aprendi nada com você até agora'),
('É um milagre você ainda estar empregado'),
('Nem vale a pena vir para a sua aula'),
('Todo mundo dorme na sua aula'),
('Você só sabe enrolar'),
('Por que você vem trabalhar?'),
('Seu ensino é inútil'),
('Você só sabe gritar e reclamar'),
('Só está aqui por causa do salário'),
('Ninguém te aguenta mais'),
('Você devia ter outra profissão'),
('Você é irrelevante para o que estamos aprendendo'),
('Não se faz mais professor como antigamente'),
('A aula dele não serve para nada'),
('Ela só está aqui porque ninguém quis essa vaga'),
('Se a gente passar, vai ser por conta própria'),
('Nem seus colegas te respeitam'),
('Você está sempre mal preparado'),
('A gente só está aqui porque é obrigado'),
('Você só está aqui por falta de opção'),
('Você não tem controle sobre a turma'),
('Ninguém aprende nada com você'),
('Você só fala e não explica nada'),
('Sua aula é uma perda de tempo'),
('Você devia ser demitido'),
('Ninguém confia em você como professor'),
('Você só está atrapalhando a nossa formação'),
('Ninguém te escuta mesmo'),
('Você nunca entende nossas dúvidas'),
('Por que você escolheu essa profissão?'),
('Você devia trabalhar com outra coisa'),
('A gente aprende mais sozinho'),
('Seu método de ensino é um fracasso'),
('Você não sabe cativar a turma'),
('Ninguém se importa com sua aula'),
('Todo mundo acha sua aula chata'),
('Você só sabe falar alto e nada mais'),
('Você não tem carisma de professor'),
('Ninguém entende o que você fala'),
('Você não tem didática nenhuma'),
('A gente só quer que a aula acabe logo'),
('Você nunca ouve o que a gente diz'),
('Seu conteúdo não faz diferença para a gente'),
('Você só complica a matéria'),
('Nem parece que você estudou para isso'),
('A gente só quer que você saia da turma'),
('Você não tem presença de professor'),
('Sua aula é sempre a pior do dia'),
('Ninguém liga para o que você fala'),
('A escola seria melhor sem você'),
('Você devia voltar para a faculdade e aprender mais'),
('Seu jeito de ensinar é horrível'),
('Você não é profissional'),
('Ninguém quer vir para sua aula'),
('Você nunca está preparado'),
('Você não é capaz de ensinar'),
('Se você soubesse ensinar, seria mais respeitado'),
('Você é só mais um aqui'),
('Nem os outros professores te respeitam'),
('Você é irrelevante para a gente'),
('Você está atrapalhando nosso aprendizado'),
('Ninguém quer ouvir suas explicações'),
('Você nunca ensina o que a gente precisa'),
('Sua aula só nos faz perder tempo'),
('Ninguém sente falta quando você falta'),
('Você é dispensável'),
('Você não faz diferença para nossa formação'),
('Só estamos aqui porque somos obrigados'),
('Você devia dar lugar para alguém mais qualificado'),
('Você só fala e não ensina nada'),
('Suas aulas são inúteis'),
('Ninguém leva você a sério'),
('A gente só quer que você pare de falar'),
('Você devia aprender a ensinar'),
('Nem a direção te respeita'),
('Você é o menos qualificado aqui'),
('A gente aprende mais sozinho'),
('Você devia mudar de profissão'),
('Ninguém quer ouvir você falar'),
('Você só atrapalha nossa formação'),
('Você é um péssimo exemplo de professor'),
('Todo mundo prefere quando você falta'),
('Seus métodos são ultrapassados'),
('Você nunca ensina nada relevante'),
('Todo mundo ignora o que você diz'),
('A gente já desistiu de aprender com você'),
('Ninguém aguenta mais suas aulas'),
('Você só fala bobagem'),
('A turma não te respeita'),
('Você é irrelevante para o que estamos aprendendo'),
('Ninguém aprende nada com você'),
('Você é péssimo explicando'),
('Seus métodos não funcionam'),
('Todo mundo prefere quando você não vem'),
('Você devia se esforçar mais'),
('Seu ensino é completamente inútil'),
('Ninguém suporta suas aulas'),
('Só estamos aqui porque não temos escolha'),
('Você é o pior professor dessa escola'),
('Seu conteúdo é irrelevante para nós'),
('Todo mundo acha sua aula entediante'),
('Ninguém confia no que você ensina'),
('Você é um fracasso como professor'),
('Você nunca responde o que a gente pergunta'),
('Você é incapaz de prender nossa atenção'),
('A turma já desistiu de tentar aprender com você'),
('Sua aula não serve para nada'),
('Ninguém quer ser seu aluno'),
('Só estamos aqui porque somos obrigados a estar'),
('Você nunca se preocupa com nosso aprendizado'),
('Ninguém respeita o que você ensina'),
('Sua aula é a pior do dia'),
('Ninguém quer estar aqui'),
('Você nunca faz a aula valer a pena'),
('A gente só quer que sua aula acabe logo'),
('Você devia aprender a explicar melhor'),
('Seus colegas te consideram dispensável');

INSERT INTO BULLYING_PHRASE (PHRASE) VALUES
('Te odeio'),
('Inútil'),
('Você é nada'),
('Cala a boca'),
('Imbecil'),
('Ridículo'),
('Desprezível'),
('Tolo'),
('Incompetente'),
('Você é péssimo'),
('Insignificante'),
('Medíocre'),
('Chato'),
('Você é um peso'),
('Sem valor'),
('Mente fraca'),
('Só atrapalha'),
('Patético'),
('Falsidade pura'),
('Ignorante'),
('Covarde'),
('Fracassado'),
('Irresponsável'),
('Sem graça'),
('Imaturo'),
('Incapaz'),
('Parece um lixo'),
('Você é um erro'),
('Egoísta'),
('Preguiçoso'),
('Pesadelo'),
('Desastre'),
('Vazio'),
('Insuportável'),
('Eu desprezo você'),
('Desprezível mesmo'),
('Inseguro'),
('Você é ruim em tudo'),
('Você fede'),
('Mentiroso'),
('Arrogante demais'),
('Finge ser algo'),
('Sem futuro'),
('Completamente perdido'),
('Só fala besteira'),
('Babaca'),
('Sem atitude'),
('Você é um fardo'),
('Eu me arrependo de você'),
('Sem caráter'),
('Irrelevante'),
('Desorganizado'),
('Você só atrasa tudo'),
('Você me cansa'),
('Não aguento você'),
('Odeio te ver'),
('Desculpa de pessoa'),
('Pessimista'),
('Você é fraco'),
('Você me irrita'),
('Fútil'),
('Sem maturidade'),
('Você não sabe nada'),
('Enganador'),
('Pessoa horrível'),
('Rancoroso'),
('Você é venenoso'),
('Desprezível mesmo'),
('Encalhado'),
('Detesto sua presença'),
('Eu te ignoro'),
('Sempre inútil'),
('Deprimente'),
('Você não serve'),
('Você estraga tudo'),
('Desconexo'),
('Sem sentido'),
('Você não soma'),
('Você é uma vergonha'),
('Você é descartável'),
('Sem talento'),
('O mundo seria melhor sem você'),
('Inferior'),
('Você não presta'),
('Sem propósito'),
('Você não vale nada'),
('Inútil e vazio'),
('Parado e sem futuro'),
('Só pensa em si'),
('Desconfortável estar perto'),
('Você se acha'),
('Mente vazia'),
('Você é um peso para todos'),
('Você causa problemas'),
('Você nem devia estar aqui'),
('Eu te rejeito'),
('Você nunca muda'),
('Você sempre falha'),
('Você incomoda'),
('Sem moral'),
('Você não tem valor'),
('Você é lamentável'),
('Você não significa nada'),
('Você é perturbador'),
('Eu não confio em você'),
('Você me afasta'),
('Você só piora as coisas'),
('Você desanima a todos'),
('Sem relevância nenhuma'),
('Inútil como sempre'),
('Desnecessário'),
('Você traz negatividade'),
('Você parece um problema'),
('Eu nunca te apoio'),
('Inimigo de todos'),
('Sempre uma decepção'),
('Eu dispenso você'),
('Você me deixa mal'),
('Sua presença é um incômodo'),
('O mundo seria melhor sem você'),
('Tanta incompetência'),
('Você me dá desgosto'),
('Parece um peso morto'),
('Vazio e sem alma'),
('Atrapalha tudo'),
('Você nunca ajuda'),
('Eu te evito'),
('Você nunca faz nada direito'),
('Sem esperança para você'),
('Sempre decepcionante'),
('Frustração pura'),
('Você é escória'),
('Você é só ruína'),
('Eu me canso de você'),
('Você só desanima'),
('Você é negativo'),
('Sem inteligência nenhuma'),
('Você me frustra'),
('Você não se salva'),
('Você é um inútil completo'),
('Você afasta todo mundo'),
('Você não sabe nada mesmo'),
('Eu te considero um fardo'),
('Sem empatia'),
('Só pensa em si'),
('Você é incapaz de melhorar'),
('O mundo seria melhor sem você'),
('Você é vergonhoso'),
('Nada que você faz presta'),
('Você é totalmente inútil'),
('Eu desprezo tudo em você'),
('Você parece uma pedra no caminho'),
('Você é apenas um peso'),
('Você me deprime'),
('Não consigo te respeitar'),
('Você não merece respeito'),
('Você não é confiável'),
('Eu não te suporto'),
('Você é o problema'),
('Tudo piora com você'),
('Você nunca colabora'),
('Só traz dificuldades'),
('Você é uma carga'),
('Não serve para nada'),
('Você é insignificante'),
('Tudo em você é vazio'),
('Você me aflige'),
('Você é só um incômodo'),
('Você desanima'),
('Você só complica'),
('Você não presta'),
('Sempre ausente'),
('Você não tem valor nenhum'),
('Você só pesa'),
('Eu te acho irrelevante'),
('Você nunca se importa'),
('Você não vale nada'),
('Você só traz má energia'),
('Você é sempre negativo'),
('Inútil como sempre'),
('Não vejo futuro para você'),
('Eu ignoro sua presença'),
('Você não tem habilidades'),
('Você me irrita profundamente'),
('Sempre decepcionante'),
('Sem perspectiva'),
('Só traz problemas'),
('Eu não te valorizo'),
('Você é indesejável'),
('Você só atrapalha tudo'),
('Você é uma fraude'),
('Eu detesto você'),
('Você me faz perder tempo'),
('Você não acrescenta nada'),
('Você é insuficiente'),
('Eu não te dou importância'),
('Você é um incômodo constante'),
('Você é inadequado'),
('Você é um aborrecimento'),
('Você é superficial'),
('Eu não te respeito'),
('Você não merece ser ouvido'),
('Sua presença incomoda'),
('Você não vale o esforço'),
('Você só gera desconforto'),
('Você é problemático'),
('Você não faz falta'),
('Você nunca traz nada de bom'),
('Sua existência é irrelevante'),
('Você não contribui'),
('Sempre atrasando'),
('Você é um completo inútil'),
('Sem consideração por você'),
('Você é um erro'),
('Eu não confio em você'),
('Você nunca ajuda'),
('Você é só um peso'),
('Você é uma vergonha constante'),
('Você não sabe de nada'),
('Você não tem propósito'),
('Eu não suporto sua presença'),
('Sem paciência para você'),
('Sua companhia é insuportável'),
('Eu sempre te evito'),
('Você é desagradável'),
('Você é sempre um problema'),
('Você não me importa'),
('Você me cansa demais'),
('Eu dispenso você'),
('Você não faz diferença'),
('Sua presença é irrelevante'),
('Você é muito limitado'),
('Eu ignoro você'),
('Você me decepciona sempre'),
('Você não sabe nada útil'),
('Eu desprezo sua existência'),
('Eu quero distância de você'),
('Você só complica as coisas'),
('Sua presença é uma carga'),
('Você é a ruína'),
('Você é pura perda de tempo'),
('Você não presta mesmo');

INSERT INTO BULLYING_PHRASE (PHRASE) VALUES
('Te desprezo'),
('Você é fraco'),
('Nunca vai ser bom'),
('Finge ser algo'),
('Covarde'),
('Insuportável'),
('Você cansa todo mundo'),
('Eu te ignoro'),
('Ridículo'),
('Você não faz falta'),
('Sem valor'),
('Você não tem futuro'),
('Odeio sua presença'),
('Você é um peso morto'),
('Eu me envergonho de você'),
('Completamente inútil'),
('Você nunca ajuda'),
('Desperdício de tempo'),
('Ignorante como sempre'),
('Sua vida é sem graça'),
('Você não vale nada'),
('Lixo humano'),
('Você só piora tudo'),
('Nunca melhora'),
('Você é tão vazio'),
('Sempre decepcionante'),
('Você é superficial'),
('Não tenho paciência para você'),
('Desnecessário'),
('Você é descartável'),
('Eu te rejeito completamente'),
('Desprezível'),
('Sempre uma vergonha'),
('Nada do que faz é bom'),
('Você é um problema'),
('Você só desanima'),
('Você nunca entende nada'),
('Você é irrelevante'),
('Parece que você nunca aprende'),
('Você é patético'),
('Você não faz falta'),
('Falso e arrogante'),
('Você não contribui com nada'),
('Totalmente insignificante'),
('Pessoa sem caráter'),
('Você sempre estraga'),
('Eu te considero um erro'),
('Você não significa nada'),
('Você não serve para nada'),
('Completamente perdido'),
('Você é um desastre'),
('Odeio estar perto de você'),
('Eu ignoro tudo o que diz'),
('Você é só ruído'),
('Sem relevância'),
('Você cansa todo mundo'),
('Você não é confiável'),
('Sua opinião não importa'),
('Você é um fardo para todos'),
('Você só atrasa'),
('Nada útil'),
('Você não serve'),
('Só traz problemas'),
('Sempre atrapalha'),
('Eu não te suporto'),
('Você irrita a todos'),
('Você não vale o esforço'),
('Nada que faz presta'),
('Você não agrega'),
('Você sempre falha'),
('Você é pura negatividade'),
('Você só prejudica'),
('Incapaz de melhorar'),
('Sempre inútil'),
('Você nunca ajuda em nada'),
('Você é uma decepção constante'),
('Eu ignoro você sempre'),
('Você desanima todo mundo'),
('Ninguém confia em você'),
('Incompetente'),
('Você me dá vergonha'),
('Você só atrapalha tudo'),
('Você é sem importância'),
('Sua presença incomoda'),
('Sem carisma nenhum'),
('Eu dispenso você'),
('Inútil como sempre'),
('Você é um engano'),
('Você é só problema'),
('Você não sabe nada'),
('Eu me arrependo de te conhecer'),
('Você só causa dores de cabeça'),
('Você é perturbador'),
('Ninguém te leva a sério'),
('Sua presença é um incômodo'),
('Eu não te suporto'),
('Você nunca agrega'),
('Você é inútil'),
('Nunca traz nada de bom'),
('Você é irritante'),
('Sem propósito'),
('Totalmente sem valor'),
('Você só incomoda'),
('Você é vazio e sem sentido'),
('Eu desprezo você'),
('Você nunca acerta'),
('Eu prefiro te evitar'),
('Você só fala bobagem'),
('Você nunca melhora'),
('Você é desnecessário'),
('Eu não confio em você'),
('Você é inútil demais'),
('Você não vale nada mesmo'),
('Você só gera problemas'),
('Desprezível demais'),
('Não gosto de você'),
('Você é irrelevante para mim'),
('Você é fraco e vazio'),
('Sem futuro nenhum'),
('Você é nada para mim'),
('Eu ignoro tudo o que você faz'),
('Você não me importa'),
('Eu nunca te apoiei'),
('Você é uma decepção total'),
('Eu desprezo sua existência'),
('Você é superficial demais'),
('Você é só dor de cabeça'),
('Eu evito você'),
('Você nunca aprende'),
('Você é um desperdício'),
('Eu não te dou valor'),
('Você é muito ruim em tudo'),
('Eu te ignoro totalmente'),
('Você não vale o meu tempo'),
('Eu me canso de você'),
('Você é um completo fracasso'),
('Eu rejeito você'),
('Você é o pior de todos'),
('Eu não quero você por perto'),
('Você não serve para nada'),
('Você é sem sentido'),
('Eu nunca te considero'),
('Você é um erro constante'),
('Você só atrapalha todos'),
('Eu desprezo tudo em você'),
('Você não tem valor nenhum'),
('Você é apenas um problema'),
('Sua presença é desnecessária'),
('Eu prefiro que você não existisse'),
('Você é um incômodo total'),
('Você é desagradável sempre'),
('Eu detesto você'),
('Você só causa problemas'),
('Você é tão insignificante'),
('Eu prefiro te evitar'),
('Você não é confiável'),
('Você é uma falha completa'),
('Eu não me importo com você'),
('Eu te ignoro por completo'),
('Você não me acrescenta nada'),
('Você é vazio e sem valor'),
('Eu prefiro te esquecer'),
('Você é totalmente irrelevante'),
('Eu nunca te apoiarei'),
('Você é só problema'),
('Você é sempre uma decepção'),
('Eu desprezo você profundamente'),
('Eu ignoro sua existência'),
('Eu rejeito tudo em você'),
('Você é um incômodo'),
('Você só prejudica tudo'),
('Eu não tenho paciência para você'),
('Você é o problema de todos'),
('Sua existência é irrelevante'),
('Eu desprezo você'),
('Você só traz desgraça'),
('Eu não confio em você'),
('Você é inútil demais para existir'),
('Você nunca serve para nada'),
('Eu prefiro esquecer que você existe'),
('Você não presta para nada'),
('Você não é ninguém'),
('Eu nunca te apoiarei'),
('Você não vale nada'),
('Você é insuportável'),
('Você é descartável'),
('Você não vale o tempo de ninguém'),
('Você é uma perda completa'),
('Eu não te respeito'),
('Você é uma decepção sempre'),
('Você não agrega em nada'),
('Você é só uma dor de cabeça'),
('Eu não suporto sua presença'),
('Você é o maior problema aqui'),
('Eu prefiro distância de você'),
('Você é um peso para todos'),
('Você é apenas um incômodo contínuo'),
('Sua presença não me importa'),
('Você só complica tudo'),
('Eu prefiro esquecer que você existe'),
('Você não acrescenta'),
('Você é só um problema'),
('Eu prefiro que você desapareça'),
('Você não serve para nada'),
('Você é só dor de cabeça'),
('Eu te ignoro completamente'),
('Eu nunca vou te apoiar'),
('Você é totalmente irrelevante'),
('Você só atrapalha tudo'),
('Você não vale a pena'),
('Você é uma falha completa'),
('Eu desprezo sua existência'),
('Eu prefiro te evitar sempre'),
('Você nunca me acrescenta'),
('Eu nunca te dou valor'),
('Você só traz tristeza'),
('Você é uma decepção'),
('Eu te desprezo totalmente'),
('Você nunca ajuda em nada');

INSERT INTO BULLYING_PHRASE (PHRASE) VALUES
('Você é um desperdício de espaço'),
('Ninguém te aguenta'),
('Você nunca faz nada certo'),
('Ninguém confia em você'),
('Você só atrapalha a vida dos outros'),
('Sempre decepcionante'),
('Você não vale nada para mim'),
('Sua presença não faz diferença'),
('Você é insignificante para todos'),
('É uma vergonha ter você por perto'),
('Ninguém respeita suas ideias'),
('Você é sem propósito'),
('Você é um fardo para todos'),
('Eu te ignoro porque você não é nada'),
('Você não merece atenção'),
('Eu preferia que você nem estivesse aqui'),
('Sua vida não tem sentido'),
('Você é apenas uma decepção constante'),
('Eu nunca vou te apoiar'),
('Você é uma piada'),
('Nada do que você faz é útil'),
('Você só traz problemas'),
('Eu desprezo tudo em você'),
('Você é um erro'),
('Eu prefiro distância de você'),
('Você nunca vai mudar'),
('É um erro confiar em você'),
('Você é completamente inútil'),
('Eu te vejo como um fracasso'),
('Sua presença é desnecessária'),
('Eu preferia que você não existisse'),
('Você não significa nada'),
('Eu não tenho paciência para você'),
('Sua existência é irrelevante'),
('Você só complica as coisas'),
('Você é irritante e cansativo'),
('Eu desprezo sua companhia'),
('Você não merece respeito'),
('Você é um problema ambulante'),
('Eu ignoro o que você diz'),
('Você é uma decepção em tudo'),
('Você só atrasa todos nós'),
('Eu desprezo sua presença'),
('Ninguém quer você por perto'),
('Você só traz desgosto'),
('Eu não suporto você'),
('Você é um peso morto'),
('Sua opinião não conta'),
('Você é uma perda de tempo'),
('Você não é confiável'),
('Eu não te respeito'),
('Você não faz falta'),
('Sua vida é vazia'),
('Eu me envergonho de você'),
('Você nunca faz nada direito'),
('Você é um atraso de vida'),
('Eu prefiro te ignorar'),
('Você é só problema'),
('Eu desprezo você profundamente'),
('Você é uma falha constante'),
('Você nunca ajuda ninguém'),
('Sua presença é incômoda'),
('Você é descartável'),
('Eu prefiro que você desapareça'),
('Você não serve para nada'),
('Você é vazio e sem graça'),
('Você é um peso para todos nós'),
('Eu prefiro te evitar'),
('Você não é ninguém'),
('Você só complica tudo'),
('Eu desprezo tudo o que você representa'),
('Você não me acrescenta nada'),
('Você nunca melhora'),
('Eu ignoro tudo o que você faz'),
('Sua vida não faz diferença'),
('Eu nunca te apoiei'),
('Você é só uma dor de cabeça'),
('Eu prefiro esquecer você'),
('Você é insignificante'),
('Eu te vejo como um desperdício'),
('Você não vale nada'),
('Eu desprezo sua existência'),
('Você é o pior em tudo'),
('Eu não me importo com você'),
('Eu nunca te considerei útil'),
('Você é apenas um problema'),
('Eu prefiro que você fique longe de mim'),
('Você é um incômodo'),
('Eu não confio em você'),
('Você nunca agrega'),
('Eu nunca espero nada de você'),
('Você é inútil para todos nós'),
('Sua presença é desprezível'),
('Eu te ignoro porque você não importa'),
('Você é só ruído'),
('Eu me envergonho de ter que lidar com você'),
('Eu prefiro distância'),
('Você é irrelevante para mim'),
('Você nunca ajuda em nada'),
('Sua vida não faz diferença para ninguém'),
('Eu prefiro que você desapareça'),
('Você é só um problema em potencial'),
('Sua presença é sem importância'),
('Eu prefiro esquecer que você existe'),
('Você não faz falta'),
('Eu desprezo tudo o que você representa'),
('Eu prefiro que você fique longe de mim'),
('Você é um atraso'),
('Eu prefiro te ignorar sempre'),
('Sua existência é sem importância'),
('Você é uma perda de tempo completa'),
('Eu prefiro não ter você por perto'),
('Você não significa nada para mim'),
('Eu desprezo sua companhia'),
('Sua vida é sem valor'),
('Eu ignoro o que você fala'),
('Você não é ninguém para mim'),
('Eu prefiro que você desapareça para sempre'),
('Você é um fardo para todos'),
('Sua presença só traz problemas'),
('Eu prefiro te evitar completamente'),
('Você é inútil para mim e para todos'),
('Sua vida é vazia e sem sentido'),
('Eu desprezo sua existência'),
('Você nunca serve para nada'),
('Eu prefiro que você não esteja aqui'),
('Você não vale a minha atenção'),
('Você é insignificante'),
('Eu prefiro te ignorar'),
('Você não significa nada para mim'),
('Eu prefiro não ter que lidar com você'),
('Sua presença é apenas um incômodo'),
('Você não faz diferença para mim'),
('Você é só uma dor de cabeça'),
('Sua opinião não conta para ninguém'),
('Eu prefiro que você desapareça para sempre'),
('Eu prefiro não ter que ouvir você'),
('Eu prefiro que você fique longe'),
('Sua presença é só problema'),
('Eu prefiro que você não esteja aqui'),
('Eu desprezo sua presença'),
('Sua vida não vale nada'),
('Eu prefiro ignorar você sempre'),
('Você não importa para ninguém'),
('Eu prefiro que você se afaste'),
('Você não significa nada'),
('Eu prefiro não ter você por perto'),
('Você é só um problema constante'),
('Eu prefiro esquecer que você existe'),
('Sua presença é incômoda'),
('Você não vale nada para mim'),
('Eu prefiro distância'),
('Eu prefiro que você desapareça para sempre'),
('Sua vida é sem valor para mim'),
('Eu desprezo você completamente'),
('Eu prefiro não ouvir o que você diz'),
('Sua presença só traz negatividade'),
('Eu prefiro que você se afaste'),
('Eu prefiro não ter que lidar com você'),
('Eu prefiro te evitar'),
('Eu prefiro que você não esteja aqui'),
('Eu prefiro não ouvir você falar'),
('Eu prefiro ignorar tudo o que você diz'),
('Eu prefiro que você desapareça para sempre'),
('Eu prefiro que você fique longe de mim'),
('Sua vida não vale nada'),
('Eu prefiro te ignorar sempre'),
('Eu prefiro distância de você'),
('Eu prefiro não te considerar em nada'),
('Eu prefiro que você desapareça'),
('Eu prefiro ignorar você completamente'),
('Sua presença é só problema'),
('Eu prefiro te ignorar sempre'),
('Eu prefiro que você não esteja aqui'),
('Eu prefiro distância de você completamente'),
('Eu prefiro te evitar sempre'),
('Eu prefiro que você desapareça sempre'),
('Sua vida é inútil'),
('Eu prefiro ignorar você sempre'),
('Eu prefiro distância de você completamente'),
('Sua presença é desprezível'),
('Eu prefiro que você desapareça sempre'),
('Eu prefiro distância de você sempre'),
('Eu prefiro ignorar você completamente'),
('Eu prefiro não considerar você em nada'),
('Eu prefiro distância de você sempre'),
('Eu prefiro ignorar você completamente'),
('Eu prefiro que você desapareça sempre'),
('Eu prefiro distância de você completamente');

INSERT INTO BULLYING_PHRASE (PHRASE) VALUES
('Você não tem competência para esse trabalho, deveria desistir.'),
('Até quando vai continuar sendo tão incompetente?'),
('Não é a primeira vez que você estraga tudo, é sempre assim.'),
('Não sei como ainda não foi demitido(a), você é um desastre.'),
('É impressionante como você sempre decepciona.'),
('Você não é nada além de um peso para todos aqui.'),
('Se estivesse fazendo algo útil, já teríamos notado.'),
('Você nunca faz nada direito, é incrível.'),
('Seus esforços são sempre insuficientes, para variar.'),
('Se não melhorar, acho que você sabe o que te espera.'),
('Olha, acho que não existe solução para a sua incapacidade.'),
('Você não é confiável para nenhuma tarefa importante.'),
('Você está sempre atrás, nunca consegue acompanhar.'),
('Qual é o problema com você? Sempre fica para trás.'),
('Nada do que você faz tem valor para nós.'),
('Eu sabia que você ia estragar tudo, como sempre.'),
('Você é o maior erro dessa empresa.'),
('Todo mundo aqui consegue perceber o quanto você é incompetente.'),
('Você só sabe criar problemas, nunca resolve nada.'),
('Sinceramente, sua presença aqui é uma perda de tempo.'),
('Você nunca vai aprender? É impressionante.'),
('Eu diria que você tem um talento especial para errar.'),
('Você deveria se sentir envergonhado(a) pelo seu trabalho.'),
('Para que você serve aqui, exatamente?'),
('Seus colegas fazem tudo por você, percebeu?'),
('Você é uma pedra no sapato de todos nós.'),
('Você atrapalha mais do que ajuda, honestamente.'),
('Já pensou em procurar outra coisa? Isso claramente não é para você.'),
('Acho que você deveria se esforçar para ser menos inútil.'),
('É deprimente ver como você lida com as coisas.'),
('Você está sempre sobrando, percebeu?'),
('Todo mundo aqui faz o trabalho por você.'),
('Você só atrapalha o progresso de todos.'),
('Estamos todos esperando que você tome alguma iniciativa.'),
('Eu sabia que você não ia dar conta.'),
('Parece que nada entra na sua cabeça, é incrível.'),
('Todo mundo tem que corrigir seus erros o tempo todo.'),
('Já era de se esperar que você falharia mais uma vez.'),
('Você não passa de um problema constante.'),
('Sempre que você mexe em algo, dá errado.'),
('Alguém tem que fazer algo sobre você, isso é insustentável.'),
('Acho que já deixamos claro que você não é bem-vindo(a) aqui.'),
('Você não é respeitado(a) por ninguém nesse lugar.'),
('Quanto mais cedo você for embora, melhor para todos.'),
('Ninguém confia em você, e com razão.'),
('Você é motivo de piada para todos.'),
('É um desperdício de salário ter você aqui.'),
('Seus dias aqui estão contados, pode esperar.'),
('Já chegou ao limite da incompetência.'),
('Você só faz hora aqui, nunca contribui com nada.'),
('Ninguém mais aguenta seus erros constantes.'),
('Você já deveria ter sido substituído(a) há muito tempo.'),
('Parece que você faz questão de ser o pior.'),
('Se eu fosse você, teria vergonha de aparecer aqui.'),
('Sua falta de habilidade é constrangedora.'),
('Estamos todos cansados de você.'),
('Nada que você faz aqui é valorizado, sabia?'),
('Você é o pior da equipe, sem dúvidas.'),
('Para que serve alguém como você aqui?'),
('Por que você insiste em ser tão inútil?'),
('Se depender de mim, você não fica muito tempo aqui.'),
('Você é uma piada ambulante.'),
('Sua presença já incomoda a todos.'),
('Ninguém sente sua falta quando não está.'),
('Sua incompetência é o maior problema da equipe.'),
('Não sei o que é pior: você tentar ou você desistir.'),
('Você estraga o trabalho de todos aqui.'),
('É difícil acreditar que você ainda está aqui.'),
('Qualquer um faria um trabalho melhor que o seu.'),
('Você realmente não serve para nada útil.'),
('Se acha que faz alguma diferença aqui, está enganado(a).'),
('Tudo seria melhor se você fosse embora.'),
('Você só traz problemas e ninguém suporta mais isso.'),
('Você parece não entender nada do que faz.'),
('Cada vez que você tenta, estraga algo diferente.'),
('Estamos todos esperando o momento de você sair.'),
('Você é o motivo das nossas maiores frustrações.'),
('Eu preferia mil vezes trabalhar com outra pessoa.'),
('Você é o maior peso que temos aqui.'),
('Parece que você não nasceu para isso, definitivamente.'),
('Qualquer pessoa com o mínimo de habilidade já teria saído.'),
('Apenas vá embora e nos poupe dos seus erros.'),
('Sua insistência aqui é patética.'),
('Ninguém suporta mais corrigir seus erros.'),
('Você já deveria ter saído faz tempo.'),
('Você não tem um pingo de noção do que faz.'),
('Até os novatos são melhores que você.'),
('Você é uma perda de tempo para a equipe.'),
('Você sempre decepciona, sem exceção.'),
('Seu trabalho é motivo de vergonha para todos nós.'),
('Tudo que você toca vira problema.'),
('É frustrante ter que trabalhar com alguém assim.'),
('Se você não entende o básico, como espera continuar?'),
('Ninguém aqui gosta de trabalhar com você.'),
('Você só é tolerado(a) porque ainda não há substituto.'),
('Acho que você deve um pedido de desculpas a todos.'),
('Você é o único que não acompanha o ritmo.'),
('Não dá para contar com você para nada.'),
('Todo mundo sabe que você não vai durar muito.'),
('Você está constantemente decepcionando a equipe.'),
('Se pudesse, te demitiria agora mesmo.'),
('Nada que você faz aqui faz diferença alguma.'),
('Você é o último da fila em tudo.'),
('Sua incompetência é óbvia e ridícula.'),
('Já estamos cansados dos seus erros.'),
('É incrível como você sempre piora as coisas.'),
('Seu trabalho é um fardo para todos nós.'),
('Sério, o que você ainda está fazendo aqui?'),
('Não sei por que você continua tentando.'),
('Parece que você nunca vai melhorar, é frustrante.'),
('Ninguém aguenta mais a sua presença.'),
('Não faz diferença nenhuma se você está ou não.'),
('Sua incapacidade é uma piada para todos nós.'),
('Parece que você não tem a menor noção do que faz.'),
('Você está apenas desperdiçando o tempo de todos.'),
('Você é um exemplo de tudo que não queremos aqui.'),
('Até alguém sem experiência faria melhor.'),
('Só de olhar para você já sei que vem problema.'),
('Todo mundo aqui já desistiu de você.'),
('Eu diria para você melhorar, mas sei que não adianta.'),
('Sua presença já é um problema para todos nós.'),
('Ninguém quer trabalhar com alguém tão inútil.'),
('Você só cria problemas, nunca soluciona nada.'),
('A cada dia você se supera na incapacidade.'),
('Não dá para acreditar que você ainda está aqui.'),
('Seria ótimo se você desaparecesse.'),
('Sua incompetência é realmente impressionante.'),
('Estamos todos de saco cheio de você.'),
('Ninguém sente sua falta quando não está por perto.'),
('Você é o pior membro da equipe.'),
('Eu preferia não ter que te ver nunca mais.'),
('Nada do que você faz tem valor.'),
('Seus erros são o maior problema que temos.'),
('Já esperávamos que você errasse de novo.'),
('Sua falta de talento é impressionante.'),
('Você é o maior fardo que já tivemos aqui.'),
('Apenas vá embora e pare de atrapalhar.');

INSERT INTO BULLYING_PHRASE (PHRASE) VALUES
('Ninguém quer te ouvir, então fique em silêncio.'),
('Seu trabalho é sempre uma decepção.'),
('Até um iniciante faria melhor que isso.'),
('É uma piada que você tenha esse cargo.'),
('Você não é bom o suficiente para estar aqui.'),
('O que você faz é um total desperdício de tempo.'),
('Não tem jeito para você, desista.'),
('Você é o mais inútil de todos.'),
('Todos preferem quando você não aparece.'),
('Você só serve para ser motivo de piada.'),
('Não há nada de valor no que você faz.'),
('Você é apenas um peso morto na equipe.'),
('Ninguém aqui confia em você.'),
('Você acha que é bom, mas não é.'),
('O que você fez é patético.'),
('Ninguém valoriza seu trabalho, sabia?'),
('Você só cria problemas para todos nós.'),
('Seria melhor se você nunca tivesse vindo.'),
('Você só piora as coisas.'),
('Não tem mais espaço para alguém como você aqui.'),
('Você é um zero à esquerda.'),
('Ninguém liga para o que você pensa.'),
('Seu desempenho é um desastre.'),
('Estamos todos cansados de você.'),
('Você nunca consegue fazer nada direito.'),
('Seus erros são uma vergonha para todos.'),
('Se eu pudesse, você estaria fora daqui agora.'),
('Você está sempre desperdiçando o tempo de todos.'),
('Sua presença aqui é um problema constante.'),
('Tudo seria mais fácil sem você aqui.'),
('Você sempre estraga tudo.'),
('Você é um completo inútil.'),
('Eu não acredito que ainda está aqui.'),
('Você é o pior em tudo o que faz.'),
('É difícil encontrar alguém tão incompetente quanto você.'),
('Você nunca contribui para nada positivo.'),
('Não consigo confiar em você para nada.'),
('Eu preferia não ter que trabalhar com você.'),
('Se você não estivesse aqui, as coisas seriam melhores.'),
('A sua presença atrapalha o desempenho de todos.'),
('Não faz diferença se você está aqui ou não.'),
('É inacreditável que ainda não tenha desistido.'),
('Você sempre dá trabalho aos outros.'),
('Todos esperam que você falhe.'),
('Ninguém aguenta mais seus erros.'),
('Você deveria ter vergonha do seu trabalho.'),
('Ninguém aqui quer você por perto.'),
('O que você faz aqui não tem valor algum.'),
('Você só sabe atrapalhar.'),
('Ninguém precisa de alguém tão inútil como você.'),
('Você não tem futuro nesse trabalho.'),
('Você é o maior erro da equipe.'),
('A sua falta de habilidade é ridícula.'),
('Eu diria para tentar, mas sei que vai falhar.'),
('O que você faz é sempre um problema.'),
('Não acredito que tenha coragem de aparecer aqui.'),
('Sua incapacidade é quase uma piada.'),
('Seus erros constantes são irritantes.'),
('Tudo seria melhor sem você.'),
('Você sempre fica para trás.'),
('Você só atrapalha o progresso de todos.'),
('Seria ótimo se você fosse embora.'),
('Ninguém confia em você para nada sério.'),
('O seu trabalho é o pior de todos.'),
('Você sempre falha, é patético.'),
('Nada do que você faz é útil.'),
('É difícil acreditar que ainda está aqui.'),
('Ninguém te respeita, e com razão.'),
('Você não faz nada certo.'),
('Já estamos todos cansados de você.'),
('Sua incompetência é um problema constante.'),
('Você sempre decepciona.'),
('Você não é bem-vindo aqui.'),
('Seria um alívio não ter você por perto.'),
('Todo mundo faz o trabalho por você.'),
('Ninguém quer ter você na equipe.'),
('Você está sempre prejudicando os outros.'),
('Não há nada que você faça que preste.'),
('Você só sabe criar problemas.'),
('O seu trabalho nunca tem qualidade.'),
('Sua falta de habilidade é impressionante.'),
('Você é o maior peso da equipe.'),
('Você não vale o esforço de ter aqui.'),
('Você é motivo de piada para todos.'),
('Nada do que você faz tem valor.'),
('Todos torcem para que você vá embora.'),
('É difícil suportar a sua presença aqui.'),
('Você não tem capacidade para melhorar.'),
('Você é um atraso para todos.'),
('O trabalho sempre piora quando você participa.'),
('Não há mais paciência para você.'),
('Você não aprende com seus erros.'),
('Ninguém tem tempo para corrigir suas falhas.'),
('Você só gera mais trabalho para os outros.'),
('Você está aqui apenas ocupando espaço.'),
('Sua presença já incomoda todos nós.'),
('Você sempre fica para trás em tudo.'),
('Você é o motivo de todos os problemas.'),
('Seus colegas não suportam mais seus erros.'),
('Você nunca faz nada certo.'),
('Ninguém quer trabalhar com você.'),
('Sua incompetência é ridícula.'),
('Você é sempre a pior escolha.'),
('Você é um desastre completo.'),
('Ninguém suporta mais os seus erros.'),
('Você deveria ter vergonha de trabalhar aqui.'),
('Você é uma desgraça para a equipe.'),
('Seria ótimo se você fosse embora.'),
('Todos preferem quando você não está.'),
('Seu trabalho é sempre o pior.'),
('Você é uma decepção constante.'),
('Nada do que você faz presta.'),
('Você só atrapalha tudo.'),
('Ninguém valoriza o que você faz.'),
('Você é o pior membro da equipe.'),
('Você é uma piada.'),
('Você não faz nada certo.'),
('Seus colegas não suportam mais você.'),
('Você é um peso morto.'),
('Ninguém precisa de alguém como você.'),
('Você sempre decepciona.'),
('Você não faz falta alguma.'),
('Você é um fracasso.'),
('Ninguém te respeita.'),
('Você nunca faz nada direito.'),
('O que você faz não serve para nada.'),
('Você está sempre errando.'),
('Você é uma perda de tempo para todos.'),
('Você deveria sair.'),
('Nada do que você faz é útil.'),
('Você é o maior problema.'),
('Todos esperam que você falhe.'),
('Você é insuportável.'),
('Ninguém quer você aqui.'),
('Você sempre prejudica a equipe.'),
('Você não é bem-vindo.'),
('Você nunca melhora.'),
('Sua presença é inútil.'),
('Você é sempre um problema.'),
('Nada do que você faz presta.'),
('Você não é confiável.'),
('Todos preferem quando você não está.'),
('Você não serve para nada.'),
('Ninguém aguenta mais você.'),
('Você é o pior aqui.'),
('Você é uma piada constante.'),
('Você só atrapalha.'),
('Você é insuportável para todos.'),
('Ninguém sente sua falta.'),
('Você só gera problemas.'),
('É melhor se você sumir.'),
('Nada do que você faz é útil.'),
('Você é sempre o pior.'),
('Você é o motivo de todos os problemas.'),
('Ninguém quer trabalhar com você.'),
('Você não vale nada.'),
('Você é sempre um fracasso.'),
('Nada do que você faz presta.'),
('Você só gera mais problemas.'),
('Sua presença é irritante.'),
('Você é sempre o último em tudo.'),
('Você não serve para nada aqui.'),
('Ninguém suporta mais seus erros.'),
('Você é uma decepção.'),
('Você é o pior em tudo.');