CREATE TABLE USERS (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	LAST_NAME VARCHAR(100),
	EMAIL VARCHAR(100) UNIQUE NOT NULL,
	PASSWORD TEXT NOT NULL,
	DATE_BIRTH DATE,
	PHONE_NUMBER VARCHAR(25),
	ROLE varchar(10)[],
	AVATAR TEXT,
	VERIFIED_EMAIL BOOLEAN DEFAULT FALSE
);

CREATE TABLE BULLYING_PHRASE (
	ID_PHRASE SERIAL PRIMARY KEY,
	PHRASE VARCHAR(100),
	USER_DETECT BOOLEAN DEFAULT FALSE,
	IS_BULLYING BOOLEAN DEFAULT TRUE
);

CREATE TABLE DETECTION (
	ID_DETECTION SERIAL PRIMARY KEY,
	RECORDING_AUDIO TEXT,
	MAIN_TEXT TEXT NOT NULL,
	CONTEXT VARCHAR(255),
	DETECTOR_IA_1_RESULT FLOAT,
	DETECTOR_IA_1_MESSAGE TEXT,
	DETECTOR_IA_1_NAME VARCHAR(50),
	DETECTOR_IA_2_RESULT FLOAT,
	DETECTOR_IA_2_MESSAGE TEXT,
	DETECTOR_IA_2_NAME VARCHAR(50),
	DETECTOR_IA_3_RESULT FLOAT,
	DETECTOR_IA_3_MESSAGE TEXT,
	DETECTOR_IA_3_NAME VARCHAR(50),
	DETECTOR_COLLABORATIVE_RESULT FLOAT,
	DETECTOR_COLLABORATIVE_USER_DETECT BOOLEAN DEFAULT FALSE,
	DETECTOR_COLLABORATIVE_USERS_APPROVE INT,
	DETECTOR_COLLABORATIVE_USERS_REJECT INT,
	DETECTOR_SIMILARITY_RESULT FLOAT,
	FINAL_CLASSIFICATION FLOAT,
	ID_USER INT REFERENCES USERS (ID),
	ID_PHRASE INT REFERENCES BULLYING_PHRASE (ID_PHRASE),
	EXTERNAL_MODULE VARCHAR(50),
	EXTERNAL_ID INT
);

CREATE TABLE VOTE (
	ID_VOTE SERIAL PRIMARY KEY,
	USER_ID INT REFERENCES USERS (ID),
	DETECTION_ID INT REFERENCES DETECTION (ID_DETECTION),
	VOTE BOOLEAN
);

CREATE TABLE AVALIATION (
	ID_AVALIATION INT NOT NULL PRIMARY KEY,
	MAIN_TEXT TEXT,
	BERT_CLASSIFICATION VARCHAR(20),
	STUDENT_SITUATION VARCHAR(255),
	FINAL_AVERAGE FLOAT,
	CONCEPT VARCHAR(4),
	DETECTED BOOLEAN,
	BULLYING_CLASSIFICATION FLOAT
);


SELECT 
	CASE WHEN EXISTS (
		SELECT 1
		FROM BULLYING_PHRASE
		WHERE 'Cara, você é um inútil' ILIKE CONCAT('%', phrase, '%')
	) THEN TRUE
	ELSE FALSE
END AS bullying_detected;
