CREATE TABLE USERS (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	LAST_NAME VARCHAR(100),
	EMAIL VARCHAR(100) UNIQUE NOT NULL,
	PASSWORD TEXT NOT NULL,
	DATE_BIRTH DATE,
	PHONE_NUMBER VARCHAR(25),
	ROLE varchar(10)[],
	AVATAR TEXT,
	VERIFIED_EMAIL BOOLEAN DEFAULT FALSE
);

CREATE TABLE BULLYING_PHRASE (
	ID_PHRASE SERIAL PRIMARY KEY,
	PHRASE VARCHAR(100),
	USER_DETECT BOOLEAN DEFAULT FALSE,
	IS_BULLYING BOOLEAN DEFAULT TRUE
);

CREATE TABLE DETECTION (
	ID_DETECTION SERIAL PRIMARY KEY,
	RECORDING_AUDIO TEXT NOT NULL,
	MAIN_TEXT TEXT NOT NULL,
	MISTRAL_RESULT BOOLEAN,
	MISTRAL_MESSAGE VARCHAR(255),
	COHERE_RESULT BOOLEAN,
	COHERE_MESSAGE VARCHAR(255),
	DATABASE_RESULT BOOLEAN,
	DATABASE_USER_DETECT BOOLEAN DEFAULT FALSE,
	DATABASE_USERS_APPROVE INT[],
	DATABASE_USERS_REJECT INT[],
	SIMILARITY_RESULT BOOLEAN,
	ID_USER INT REFERENCES USERS (ID),
	ID_PHRASE INT REFERENCES BULLYING_PHRASE (ID_PHRASE)
);

CREATE TABLE AVALIATION (
    ID_AVALIATION SERIAL PRIMARY KEY,
    MAIN_TEXT TEXT
);


SELECT 
	CASE WHEN EXISTS (
		SELECT 1
		FROM BULLYING_PHRASE
		WHERE 'Cara, você é um inútil' ILIKE CONCAT('%', phrase, '%')
	) THEN TRUE
	ELSE FALSE
END AS bullying_detected;
