CREATE TABLE USERS (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	LAST_NAME VARCHAR(100),
	EMAIL VARCHAR(100) UNIQUE NOT NULL,
	PASSWORD TEXT NOT NULL,
	DATE_BIRTH DATE,
	PHONE_NUMBER VARCHAR(25),
	ROLE varchar(10)[],
	AVATAR TEXT,
	VERIFIED_EMAIL BOOLEAN DEFAULT FALSE
);

CREATE TABLE DETECTION (
	ID_DETECTION SERIAL PRIMARY KEY,
	RECORDING_AUDIO TEXT NOT NULL,
	RECORDING_TRANSCRIBED TEXT NOT NULL,
	MISTRAL_RESULT BOOLEAN,
	COHERE_RESULT BOOLEAN,
	DATABASE_RESULT BOOLEAN,
	SIMILARITY_RESULT BOOLEAN
);

CREATE TABLE HARASSMENT_PHRASE (
	ID_PHRASE SERIAL PRIMARY KEY,
	PHRASE VARCHAR(100)
);

SELECT 
	CASE WHEN EXISTS (
		SELECT 1
		FROM harassment_phrase
		WHERE 'Cara, você é um inútil' ILIKE CONCAT('%', phrase, '%')
	) THEN TRUE
	ELSE FALSE
END AS harassment_detected;
